# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StackUIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for StackUIExample
  pod 'StackUI', :path => '../../StackUI'
  pod 'StackUI/RxSwift', :path => '../../StackUI'

end
